### PR TITLE
Empty to default 2

### PR DESCRIPTION
**Pull request by StringEpsilon**
I rebased the changes in #20 ( Feature/empty to default )  to main with some style and formatting changes. Was easier than trying for a proper merge with current main.

I also noticed that some of the `Nullable<>` handling didn't work properly for some target types, so I patched too.

### CODE REVIEW

**Comment by StringEpsilon** [comment]
@sommmen can you have a look? I think I got all your changes intact and the tests you wrote all pass too.

**Comment by sommmen** [comment]
> @sommmen can you have a look? I think I got all your changes intact and the tests you wrote all pass too.

I'll take a look tomorrow if i got the time. In my main app I was running into an issue with the 0.9 code where the app faulted setting an empty string to a class l, something like a:1:{s:0:""} could not be parsed to a custom class (ExtraMetaPhpModel).

I'll have to recheck the exact case tho.

You can also just go ahead and release this. If the test passed I'm confident things will go through and I can instantly check the new version against my own app.

**Comment by StringEpsilon** [comment]
I still have some things I want to get done for 0.10. Will probably release on the weekend, maybe early next week. So, no hurry :)

**Comment by sommmen** [comment]
Welp TIL how to get upstream branches into a forked repo - lol.

Anyway i checked out your branch and took a gander over my original changes - LGTM .

My main app now faults over the following case:

Exception:
```
DeserializationException: Can not assign value "" (at position 9) to target type of KpsShippingExtraMetaPhpModel
```

Value to Deserialize:
``` 
a:1:{i:0;s:0:"";}
```

Model(s):
``` csharp
public class KpsShippingExtraMetaPhpModel
{
	[PhpProperty("labelId")]
	public string LabelId { get; set; } 

	[PhpProperty("trackerCode")]
	public string TrackerCode { get; set; }

	[PhpProperty("parcelType")]
	public string ParcelType { get; set; }

	[PhpProperty("pieceNumber")]
	public string PieceNumber { get; set; }

	[PhpProperty("weight")]
	public double Weight { get; set; }

	[PhpProperty("labelType")]
	public string LabelType { get; set; }

	[PhpProperty("dimensions")]
	public KpsShippingExtraMetaDimensionsPhpModel Dimensions { get; set; }
}

public class KpsShippingExtraMetaDimensionsPhpModel
{
    [PhpProperty("length")]
    public double Length { get; set; }

    [PhpProperty("width")]
    public double Width { get; set; }

    [PhpProperty("height")]
    public double Height { get; set; }
}
```

Code:
``` csharp
PhpDeserializationOptions PhpDeserializationOptions { get; set; } = new()
        {
            // Needed for ParcelAllocation, which may or may not have 'supports'.
            AllowExcessKeys = true
        };
PhpSerialization.Deserialize<TPhpModel>(valueString, PhpDeserializationOptions);
```

So a test is needed for that if possible.

**Comment by sommmen** [comment]
Hm - this is a tough one i've added these tests:

``` csharp
[TestMethod]
public void Enabled_ClassArrayEmptyStringEntryToClassDictionary() {
	var result = PhpSerialization.Deserialize<SimpleClass>(
		"a:1:{i:0;s:0:\"\";}"
	);

	Assert.AreEqual(result, default);
}

[TestMethod]
public void Enabled_ClassArrayEmptyStringEntryToClassDictionaryWithAllowExcessKeys() {
	var result = PhpSerialization.Deserialize<SimpleClass>(
		"a:1:{i:0;s:0:\"\";}", new PhpDeserializationOptions() {
			AllowExcessKeys = true
		}
	);

	Assert.AreEqual(result, default);
}
```

Which gives the following results:

```

Test method PhpSerializerNET.Test.Deserialize.Options.EmptyStringToDefaultTest.Enabled_ClassArrayEmptyStringEntryToClassDictionary threw exception: 
PhpSerializerNET.DeserializationException: Could not bind the key "0" to object of type SimpleClass: No such property.
    at PhpSerializerNET.PhpDeserializer.MakeObject(Type targetType, PhpSerializeToken token) in C:\Repos\PhpSerializerNET\PhpSerializerNET\PhpDeserializer.cs:line 323
   at PhpSerializerNET.PhpDeserializer.DeserializeToken(Type targetType, PhpSerializeToken token) in C:\Repos\PhpSerializerNET\PhpSerializerNET\PhpDeserializer.cs:line 184
   at PhpSerializerNET.PhpDeserializer.Deserialize[T]() in C:\Repos\PhpSerializerNET\PhpSerializerNET\PhpDeserializer.cs:line 40
   at PhpSerializerNET.PhpSerialization.Deserialize[T](String input, PhpDeserializationOptions options) in C:\Repos\PhpSerializerNET\PhpSerializerNET\PhpSerialization.cs:line 61
   at PhpSerializerNET.Test.Deserialize.Options.EmptyStringToDefaultTest.Enabled_ClassArrayEmptyStringEntryToClassDictionary() in C:\Repos\PhpSerializerNET\PhpSerializerNET.Test\Deserialize\Options\EmptyStringToDefault.cs:line 210
```
```

Assert.AreEqual failed. Expected:<PhpSerializerNET.Test.DataTypes.SimpleClass>. Actual:<(null)>. 
   at PhpSerializerNET.Test.Deserialize.Options.EmptyStringToDefaultTest.Enabled_ClassArrayEmptyStringEntryToClassDictionaryWithAllowExcessKeys()
```

So if using `AllowExcessKeys = false` then it looks liker there is a bug:

image

Apperently a token gets generated with 2 child tokens, one for `"0"` and one for `""` - that doesn't look too right but perhaps that is intended behaviour?

When using `AllowExcessKeys = true` an new class gets constructed with default values. 

image


I had expected `null` here. Perhaps if no properties could be assigned we could return null? I'm not really sure what a consumer would expect here generally.  Dealing with a class that has its properties set to default is unfortunate however, because its hard to detect this.

I.e. if `null` is returned i can branch of that, but if an 'empty' class is returned i know nothing..

To demonstrate:
image

btw: Expected and actual should be flipped in my samples.

Let me know if you can take a look at this. I would also have some time tomorrow i think so if you could give some pointers, or your thoughts on what the intended behaviour should be let me know.

Also seems like the editorconfig changes are picked up nicely by VS as is evident by the brackets on the if statement.

**Comment by StringEpsilon** [comment]
I'd expect `"a:1:{i:0;s:0:\"\";}"` to fail with the exact exception you get. 
The way PHP array data works is that you have a series of key-values. First item is the key, second is the value, and so on. The library handles that a bit inellegantly (due to how I wrote the tokenizer), but the result is still correct. `0` is the key and `""` is the value. 

In the deserialization from the token-tree, it tries to assign the key "0" to your object - and fails, because "0" can't be a property name.

I'm not sure what the expected result in the second test of yours (`Enabled_ClassArrayEmptyStringEntryToClassDictionaryWithAllowExcessKeys`) should be. I'd not be surprised by a `null`, but my intuition says the current approach of creating the instance w/o assigning any properties is still valid. After all, the array exists, it just has no (usable) values. Similarly, I'd expect `O:11:"SimpleClass":0:{}` to still give me an instance of `SimpleClass`.  Compare to the test `ExplicitToEmptyList` in  `ArrayDeserialization.cs`

Probably worthy of another flag in the options. Should be easy enough to short-circuit a "null" / default if the array or object has zero children. You can do that in `DeserializeToken()` - simply check if the current token has zero children and return default.

And a check to see if there  was at least one successful member assignment should also be reasonably easy to add. The easiest but kinda inelegant way would be to track a flag like `hasMemberAssigned` or something in `MakeObject()` and `MakeStruct()` respectively.

**Comment by sommmen** [comment]
> I'd expect `"a:1:{i:0;s:0:\"\";}"` to fail with the exact exception you get. The way PHP array data works is that you have a series of key-values. First item is the key, second is the value, and so on. The library handles that a bit inellegantly (due to how I wrote the tokenizer), but the result is still correct. `0` is the key and `""` is the value.
> 
> In the deserialization from the token-tree, it tries to assign the the value `""` to a property named "0" on your object - and fails, because "0" is not (and can't be) a property name.
> 
> I'm not sure what the expected result in the second test of yours (`Enabled_ClassArrayEmptyStringEntryToClassDictionaryWithAllowExcessKeys`) should be. I'd not be surprised by a `null`, but my intuition says the current approach of creating the instance w/o assigning any properties is still valid. After all, the array exists, it just has no (usable) values. Similarly, I'd expect `O:11:"SimpleClass":0:{}` to still give me an instance of `SimpleClass`. Compare to the test `ExplicitToEmptyList` in `ArrayDeserialization.cs`
> 
> Probably worthy of another flag in the options. Should be easy enough to short-circuit a "null" / default if the array or object has zero children. You can do that in `DeserializeToken()` - simply check if the current token has zero children and return default.
> 
> And a check to see if there was at least one successful member assignment should also be reasonably easy to add. The easiest but kinda inelegant way would be to track a flag like `hasMemberAssigned` or something in `MakeObject()` and `MakeStruct()` respectively.

Hiya,

Hm - welp looking at your remarks I feel like as it is now the results are correct. 
In some way i feel like `MakeObject` should just fault when encountering a php array with integers rather than strings but in a way its now possible to do this (i think):

``` csharp
// a:2:{i:0;s:3:"1b1";i:1;s:2:"1b";}

class Obj {
  [PhpProperty("0")]
   public string Prop0 {get;set;}

  [PhpProperty("1")]
   public string Prop1 {get;set;}
}
```

But still it feels awkward to set a 'collection' to an object.

I do like your last comments on the short circuit / extra flag. At this time i'd rather have a faster 1.0 release and i'll see if i can handle this in my appcode somehow.

As a sidenote:
Perhaps nullable context types would be a good fit for this library. Its  abit of a hassle to get into but once you get used to it its quite cool. Need the latest c# though because otherwise the static analysis can give a lot of false-positives.
https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references

**Pull request merged**
